insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6001, '44 Daystar Terrace', '', 'Galtek', 'Manitoba', 'Canada', 'U1P1Y8');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6002, '6425 Debra Avenue', '', 'Byahoml’', 'Northwest Territories', 'Canada', 'S8N9S3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6003, '66876 Onsgard Park', '', 'Hongmen', 'Ontario', 'Canada', 'I7G0Y6');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6004, '0 Lunder Road', '', 'Mullsjö', 'Ontario', 'Canada', 'J2W1L6');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6005, '4 Mifflin Pass', '', 'Mujães', 'Newfoundland and Labrador', 'Canada', 'E7A5F0');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6006, '20 Graceland Road', '', 'Shazi', 'Newfoundland and Labrador', 'Canada', 'Q5W2M0');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6007, '5268 Morning Lane', '', 'Pawonków', 'Manitoba', 'Canada', 'H4B6H8');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6008, '197 Tony Circle', '', 'Xuetian', 'Ontario', 'Canada', 'B7S1P5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6009, '34 Shoshone Parkway', '', 'Garunggang', 'Yukon', 'Canada', 'P8F2F9');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6010, '80113 Pearson Road', '', 'Bandung', 'Yukon', 'Canada', 'U5U4A4');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6011, '1 Southridge Street', '', 'Yujia', 'Manitoba', 'Canada', 'O5I8R7');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6012, '784 Aberg Junction', '', 'Talalayivka', 'Ontario', 'Canada', 'P4V1A0');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6013, '99733 Saint Paul Place', '', 'Belogorsk', 'Ontario', 'Canada', 'E4C8P4');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6014, '157 Lotheville Drive', '', 'Natonin', 'Northwest Territories', 'Canada', 'Q1O7A4');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6015, '62 Schmedeman Avenue', '', 'Guxi', 'Nunavut', 'Canada', 'P0Y0G3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6016, '9 Hanover Hill', '', 'Viterbo', 'Ontario', 'Canada', 'M7X8V3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6017, '20 Karstens Park', '', 'Sibut', 'Nunavut', 'Canada', 'U3U0D3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6018, '76 Lakewood Drive', '', 'San Javier', 'Northwest Territories', 'Canada', 'V1E0A5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6019, '76 Carioca Circle', '', 'Naushki', 'Prince Edward Island', 'Canada', 'I2Q7G5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6020, '27732 Oak Valley Parkway', '', 'San Pedro', 'Saskatchewan', 'Canada', 'P9E6L0');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6021, '7 Northport Place', '', 'Nianqiao', 'Yukon', 'Canada', 'X5T8Z5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6022, '75035 Sugar Hill', '', 'Munjungan', 'Prince Edward Island', 'Canada', 'T9K3W1');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6023, '5 Stone Corner Avenue', '', 'Wichit', 'Alberta', 'Canada', 'V4P2I0');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6024, '4363 Drewry Center', '', 'Shinpokh', 'Manitoba', 'Canada', 'M9U1T6');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6025, '1 Sundown Alley', '', 'Menlou', 'Newfoundland and Labrador', 'Canada', 'P3S3F0');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6026, '503 Dorton Parkway', '', 'Columbus', 'British Columbia', 'Canada', 'Y9I7H4');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6027, '37 Golf Course Center', '', 'Vilar', 'New Brunswick', 'Canada', 'K6E5F1');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6028, '14148 Warner Center', '', 'Modderfontein', 'Saskatchewan', 'Canada', 'E7J4G3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6029, '252 Cambridge Terrace', '', 'Qaffīn', 'Alberta', 'Canada', 'B5O5N5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6030, '03 Glendale Court', '', 'Kamo', 'Prince Edward Island', 'Canada', 'E3Q4E7');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6031, '478 Dunning Alley', '', 'Hunkuyi', 'New Brunswick', 'Canada', 'B1L5I9');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6032, '02 Southridge Center', '', 'Langob', 'Saskatchewan', 'Canada', 'D1Q1M6');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6033, '15940 Goodland Point', '', 'Foxrock', 'Northwest Territories', 'Canada', 'H2P7P5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6034, '28362 Loomis Avenue', '', 'Shangdian', 'Quebec', 'Canada', 'B4O0A2');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6035, '81621 Dottie Plaza', '', 'Thatta', 'Quebec', 'Canada', 'Y1E2O2');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6036, '53109 Farragut Way', '', 'Xihuaiba', 'New Brunswick', 'Canada', 'I1V4Y3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6037, '22808 Canary Parkway', '', 'Miān Channūn', 'Manitoba', 'Canada', 'Y8H5K9');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6038, '84948 6th Drive', '', 'Koani Ndogo', 'Northwest Territories', 'Canada', 'C3N7R5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6039, '67 Merry Trail', '', 'Gangba', 'Northwest Territories', 'Canada', 'G5X4A5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6040, '6 Rutledge Crossing', '', 'Kórnik', 'Quebec', 'Canada', 'P3Y4K1');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6041, '33080 Dennis Center', '', 'Santa Rosa', 'Quebec', 'Canada', 'Z3K9O6');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6042, '5 Stoughton Terrace', '', 'Kalapagenep', 'Newfoundland and Labrador', 'Canada', 'D3B4I3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6043, '1833 Fair Oaks Hill', '', 'Pop Shahri', 'Manitoba', 'Canada', 'H3V1M3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6044, '80621 Oak Trail', '', 'Krasnaya Polyana', 'New Brunswick', 'Canada', 'O0Q7K3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6045, '570 Pleasure Crossing', '', 'Bongor', 'British Columbia', 'Canada', 'I0U5P8');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6046, '3366 Corben Place', '', 'Banyupoh', 'Northwest Territories', 'Canada', 'S3R6C4');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6047, '217 Mallard Drive', '', 'Ōmura', 'Nunavut', 'Canada', 'V8T8W5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6048, '683 Wayridge Park', '', 'Revelstoke', 'Northwest Territories', 'Canada', 'Z9H9S0');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6049, '3762 Shelley Point', '', 'Zaoshi', 'Manitoba', 'Canada', 'B0V6J5');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6050, '11 Ridgeview Street', '', 'Beiquan', 'Nunavut', 'Canada', 'P1Z0A9');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6051, '86 Caliangt Street', '', 'Biyang', 'Ontario', 'Canada', 'B0P9W6');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6052, '7 Golden Leaf Point', '', 'Tulsa', 'Yukon', 'Canada', 'R3L7D3');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6053, '47324 Butterfield Place', '', 'Tarangnan', 'Manitoba', 'Canada', 'Z0E7Y6');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6054, '55734 Stoughton Place', '', 'Monte Leite', 'Northwest Territories', 'Canada', 'T9T5J9');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6055, '77 Bobwhite Circle', '', 'Amadora', 'Manitoba', 'Canada', 'U0T3H7');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6056, '5323 Toban Center', '', 'Xiangyangpu', 'Saskatchewan', 'Canada', 'P0H6Y7');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6057, '5 Parkside Road', '', 'Narutochō-mitsuishi', 'Northwest Territories', 'Canada', 'V3Y6B2');
insert into address (addressID, addressLine1, addressLine2, city, provinceCode, country, postalCode) values (6058, '40359 Washington Hill', '', 'Rangmanten', 'Nunavut', 'Canada', 'C9G0O3');
